name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: 'Create env file'
        run: echo "${{ secrets.ENV_FILE }}" > .env
      - name: jest tests        
        run: npm run test
      # - name: e2e tests
      #   uses: cypress-io/github-action@v4
      #   with:
      #     build: npm run build
      #     integration: npm run integration
      #     start: npm run start-prod
      #     wait-on: http://localhost:3003